# SPDX-FileCopyrightText: 2024 Osnabrück University of Applied Sciences
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

services:
  reverse_proxy:
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ./secrets/certs/acme:/acme
    labels:
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entryPoints.https.transport.respondingTimeouts.readTimeout=0
      - --entrypoints.edge.address=:8000
      - --entryPoints.edge.transport.respondingTimeouts.readTimeout=0

      - --certificatesresolvers.cloudflare.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/acme/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=${ACME_DNS_CHALLENGE_PROVIDER}
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers[0]=1.1.1.1:53
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers[1]=1.0.0.1:53

  build_container:
    volumes:
      - ./secrets/certs/acme/${PROJECT_BASE_URL}.crt:/etc/docker/certs.d/registry.${PROJECT_BASE_URL}/ca.crt

  frontend:
    labels:
      - traefik.http.routers.frontend.tls.certresolver=cloudflare

  backend:
    labels:
      - traefik.http.routers.backend.tls.certresolver=cloudflare

  keycloak:
    labels:
      - traefik.http.routers.keycloak.tls.certresolver=cloudflare

  portainer:
    labels:
      - traefik.http.routers.portainer.tls.certresolver=cloudflare

  fuseki:
    labels:
      - traefik.http.routers.fuseki.tls.certresolver=cloudflare

  webvowl:
    labels:
      - traefik.http.routers.webvowl.tls.certresolver=cloudflare

  minio:
    labels:
      - traefik.http.routers.minio.tls.certresolver=cloudflare
      - traefik.http.routers.minio-console.tls.certresolver=cloudflare

  registry:
    labels:
      - traefik.http.routers.registry.tls.certresolver=cloudflare

  cvat_server:
    labels:
      - traefik.http.routers.cvat.tls.certresolver=cloudflare

  cvat_ui:
    labels:
      - traefik.http.routers.cvat_ui.tls.certresolver=cloudflare

  prometheus:
    labels:
      - traefik.http.routers.prometheus.tls.certresolver=cloudflare

  grafana:
    labels:
      - traefik.http.routers.grafana.tls.certresolver=cloudflare

  edc_provider:
    labels:
      - traefik.http.routers.edc-provider.tls.certresolver=cloudflare
      - traefik.http.routers.edc-provider-web.tls.certresolver=cloudflare
      - traefik.http.routers.edc-provider-ids.tls.certresolver=cloudflare

  nuclio:
    labels:
      - traefik.http.routers.nuclio.tls.certresolver=cloudflare

  jupyterhub:
    labels:
      - traefik.http.routers.jupyterhub.tls.certresolver=cloudflare
